### 라이브러리 선언

In [10]:
# 데이터 처리 관련 라이브러리
import pandas as pd
# 수와 관련된 계산 라이브러리
import numpy as np

### 1. 데이터 불러오기

In [11]:
# 데이터 불러오기
customerData = pd.read_csv("../dataset/customerdata.csv")
# 데이터 저장하기
customerData.to_csv("./outdata.csv", index=False)

In [12]:
# 고객의 PAINPOINT..
customerData.describe()

          AVGPRICE         EMI  DEVICECOUNT  PRODUCTAGE
count   150.000000  150.000000   150.000000  150.000000
mean   3432.741108    2.053333     4.973333    1.932601
std     371.571877    0.445510     0.996279    0.807457
min    2390.083736    1.000000     3.000000    0.800000
25%    3214.543122    2.000000     4.000000    1.000000
50%    3408.300000    2.000000     5.000000    2.077000
75%    3664.767001    2.000000     6.000000    2.574525
max    4296.873743    3.000000     6.000000    3.483573

### 1. 데이터 행 조회하기

In [13]:
customerData.head(2)

   CUSTID    AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.90000    3            6    1.679181  Big-Screen-lover
1  A14219  3642.44195    2            4    2.682023      Sleeping-dog

In [14]:
# 조건은 데이터 타입을 정확히 맞춰 줘야한다
targetEmi = "3"
# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ (customerData.EMI == targetEmi)]
resultData

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE]
Index: []

In [15]:
# 다중 조건은 각 조건을 괄호로 묶어줘야 한다.
targetEmi = 3
targetPrice = 4000
# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ (customerData.EMI == targetEmi) &
            (customerData.AVGPRICE >= targetPrice)     ]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
113  T11473  4165.700000    3            6    1.780674  Big-Screen-lover
130  W13404  4296.873743    3            6    1.100000        Early-bird

In [16]:
## 특정 컬럼에 대한 다중 값 조회 시 isin
## 해당 부정 표현 NOT IN isin 조건 앞에 ~ 를 붙여주면 된다.
targetEmiList = [1,3]

# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ ~customerData.EMI.isin(targetEmiList) ]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog
3    A16605  3713.211107    2            6    0.900000        Early-bird
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog
5    B16849  3755.263391    2            4    2.786665      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
144  Z12772  3029.600000    2            4    2.093035  Big-Screen-lover
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2            6    1.200000        Early-bird

[120 rows x 6 columns]

### 데이터 타입 변환

In [17]:
# 데이터 타입 확인
customerData.dtypes
# EMI 컬럼 INT -> FLOAT
customerData["EMI"] =customerData.EMI.astype(float)

In [18]:
# 인덱스로도 조회가 가능하다
targetIndex = [0,1,3]
customerData.loc[ targetIndex ]

   CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover
1  A14219  3642.441950  2.0            4    2.682023      Sleeping-dog
3  A16605  3713.211107  2.0            6    0.900000        Early-bird

### 2. 데이터 컬럼 조회

In [19]:
# 컬럼 이름으로 데이터 조회하기
targetColumns = ["CUSTID","EMI"]
customerData.loc[:, targetColumns ]
customerData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover
1    A14219  3642.441950  2.0            4    2.682023      Sleeping-dog
2    A15312  3653.884565  2.0            5    3.208202      Sleeping-dog
3    A16605  3713.211107  2.0            6    0.900000        Early-bird
4    B10634  3391.074215  2.0            4    2.453656      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
145  Z13253  3678.800000  2.0            5    2.463670  Big-Screen-lover
146  Z13534  3662.437527  3.0            6    0.900000        Early-bird
147  Z16428  3516.500000  2.0            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000  2.0            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183  2.0            6    1.200000        Early-bird

[150 rows x 6 columns]

In [20]:
targetColumns = ["CUSTID","EMI"]
customerData.loc[:, ["CUSTID","EMI"]]

     CUSTID  EMI
0    A13566  3.0
1    A14219  2.0
2    A15312  2.0
3    A16605  2.0
4    B10634  2.0
..      ...  ...
145  Z13253  2.0
146  Z13534  3.0
147  Z16428  2.0
148  Z16735  2.0
149  Z19835  2.0

[150 rows x 2 columns]

In [21]:
# 인덱스 컬럼을 조회하기
# customerData.iloc[:, [0,3] ]

In [22]:
# EMI 유형이 2보다 크고 선택 컬럼[CUSTID, AVGPRICE, EMI]
targetColumns = ["CUSTID","AVGPRICE","EMI"]
emi3CsData =customerData.loc[ customerData.EMI > 2,  targetColumns]
emi3OverData = emi3CsData.reset_index(drop=True)
emi3OverData.head(2)

   CUSTID     AVGPRICE  EMI
0  A13566  4273.900000  3.0
1  F17131  3179.708359  3.0

### 3. 데이터 조작하기 (DB: CASE WHEN)

In [23]:
customerData["PRODUCTAGE_NEW"] = \
    np.where( customerData.PRODUCTAGE < 1, 1, customerData.PRODUCTAGE)
# 본인이 작성한 코드에 대한 검증 로직
# customerData.loc[ (customerData.PRODUCTAGE < 1) &
#                   (customerData.PRODUCTAGE_NEW != 1 ]

customerData.loc[ (customerData.PRODUCTAGE >= 1) &
                  (customerData.PRODUCTAGE_NEW != customerData.PRODUCTAGE) ]

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE, PRODUCTAGE_NEW]
Index: []

In [24]:
customerData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW
0,A13566,4273.900000,3.0,6,1.679181,Big-Screen-lover,1.679181
1,A14219,3642.441950,2.0,4,2.682023,Sleeping-dog,2.682023
2,A15312,3653.884565,2.0,5,3.208202,Sleeping-dog,3.208202
3,A16605,3713.211107,2.0,6,0.900000,Early-bird,1.000000
4,B10634,3391.074215,2.0,4,2.453656,Sleeping-dog,2.453656
...,...,...,...,...,...,...,...
145,Z13253,3678.800000,2.0,5,2.463670,Big-Screen-lover,2.463670
146,Z13534,3662.437527,3.0,6,0.900000,Early-bird,1.000000
147,Z16428,3516.500000,2.0,5,2.371301,Big-Screen-lover,2.371301
148,Z16735,3300.100000,2.0,5,1.704942,Big-Screen-lover,1.704942
149,Z19835,3326.526183,2.0,6,1.200000,Early-bird,1.200000

In [25]:
customerData["PRODUCTAGE_NEW"] = \
    np.where( customerData.PRODUCTAGE < 1, 1, customerData.PRODUCTAGE)

In [26]:
# 다중 조건 활용 np.where 적용 문법
customerData["PRODUCTAGE_NEW"] = \
    np.where( customerData.PRODUCTAGE < 1, 1, 
             np.where( customerData.PRODUCTAGE < 2, 2,
                      np.where( customerData.PRODUCTAGE < 3, 3, customerData.PRODUCTAGE)))