### 라이브러리 선언

In [1]:
# 데이터 처리 관련 라이브러리
import pandas as pd
# 수와 관련된 계산 라이브러리
import numpy as np

### 1. 데이터 불러오기

In [2]:
# 데이터 불러오기
customerData = pd.read_csv("../dataset/customerdata.csv")
# 데이터 저장하기
customerData.to_csv("./outdata.csv", index=False)

In [3]:
# 고객의 PAINPOINT..
customerData.describe()

          AVGPRICE         EMI  DEVICECOUNT  PRODUCTAGE
count   150.000000  150.000000   150.000000  150.000000
mean   3432.741108    2.053333     4.973333    1.932601
std     371.571877    0.445510     0.996279    0.807457
min    2390.083736    1.000000     3.000000    0.800000
25%    3214.543122    2.000000     4.000000    1.000000
50%    3408.300000    2.000000     5.000000    2.077000
75%    3664.767001    2.000000     6.000000    2.574525
max    4296.873743    3.000000     6.000000    3.483573

### 1. 데이터 행 조회하기

In [4]:
customerData.head(2)

   CUSTID    AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.90000    3            6    1.679181  Big-Screen-lover
1  A14219  3642.44195    2            4    2.682023      Sleeping-dog

In [5]:
# 조건은 데이터 타입을 정확히 맞춰 줘야한다
targetEmi = "3"
# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ (customerData.EMI == targetEmi)]
resultData

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE]
Index: []

In [6]:
# 다중 조건은 각 조건을 괄호로 묶어줘야 한다.
targetEmi = 3
targetPrice = 4000
# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ (customerData.EMI == targetEmi) &
            (customerData.AVGPRICE >= targetPrice)     ]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
113  T11473  4165.700000    3            6    1.780674  Big-Screen-lover
130  W13404  4296.873743    3            6    1.100000        Early-bird

In [7]:
## 특정 컬럼에 대한 다중 값 조회 시 isin
## 해당 부정 표현 NOT IN isin 조건 앞에 ~ 를 붙여주면 된다.
targetEmiList = [1,3]

# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ ~customerData.EMI.isin(targetEmiList) ]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog
3    A16605  3713.211107    2            6    0.900000        Early-bird
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog
5    B16849  3755.263391    2            4    2.786665      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
144  Z12772  3029.600000    2            4    2.093035  Big-Screen-lover
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2            6    1.200000        Early-bird

[120 rows x 6 columns]

### 데이터 타입 변환

In [8]:
# 데이터 타입 확인
customerData.dtypes
# EMI 컬럼 INT -> FLOAT
customerData["EMI"] =customerData.EMI.astype(float)

In [9]:
# 인덱스로도 조회가 가능하다
targetIndex = [0,1,3]
customerData.loc[ targetIndex ]

   CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover
1  A14219  3642.441950  2.0            4    2.682023      Sleeping-dog
3  A16605  3713.211107  2.0            6    0.900000        Early-bird

### 2. 데이터 컬럼 조회

In [10]:
# 컬럼 이름으로 데이터 조회하기
targetColumns = ["CUSTID","EMI"]
customerData.loc[:, targetColumns ]
customerData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover
1    A14219  3642.441950  2.0            4    2.682023      Sleeping-dog
2    A15312  3653.884565  2.0            5    3.208202      Sleeping-dog
3    A16605  3713.211107  2.0            6    0.900000        Early-bird
4    B10634  3391.074215  2.0            4    2.453656      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
145  Z13253  3678.800000  2.0            5    2.463670  Big-Screen-lover
146  Z13534  3662.437527  3.0            6    0.900000        Early-bird
147  Z16428  3516.500000  2.0            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000  2.0            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183  2.0            6    1.200000        Early-bird

[150 rows x 6 columns]

In [11]:
targetColumns = ["CUSTID","EMI"]
customerData.loc[:, ["CUSTID","EMI"]]

     CUSTID  EMI
0    A13566  3.0
1    A14219  2.0
2    A15312  2.0
3    A16605  2.0
4    B10634  2.0
..      ...  ...
145  Z13253  2.0
146  Z13534  3.0
147  Z16428  2.0
148  Z16735  2.0
149  Z19835  2.0

[150 rows x 2 columns]

In [12]:
# 인덱스 컬럼을 조회하기
# customerData.iloc[:, [0,3] ]

In [13]:
# EMI 유형이 2보다 크고 선택 컬럼[CUSTID, AVGPRICE, EMI]
targetColumns = ["CUSTID","AVGPRICE","EMI"]
emi3CsData =customerData.loc[ customerData.EMI > 2,  targetColumns]
emi3OverData = emi3CsData.reset_index(drop=True)
emi3OverData.head(2)

   CUSTID     AVGPRICE  EMI
0  A13566  4273.900000  3.0
1  F17131  3179.708359  3.0

### 3. 데이터 조작하기 (DB: CASE WHEN)

In [14]:
customerData["PRODUCTAGE_NEW"] = \
    np.where( customerData.PRODUCTAGE < 1, 1, customerData.PRODUCTAGE)
# 본인이 작성한 코드에 대한 검증 로직
# customerData.loc[ (customerData.PRODUCTAGE < 1) &
#                   (customerData.PRODUCTAGE_NEW != 1 ]

customerData.loc[ (customerData.PRODUCTAGE >= 1) &
                  (customerData.PRODUCTAGE_NEW != customerData.PRODUCTAGE) ]

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE, PRODUCTAGE_NEW]
Index: []

In [15]:
customerData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW
0,A13566,4273.900000,3.0,6,1.679181,Big-Screen-lover,1.679181
1,A14219,3642.441950,2.0,4,2.682023,Sleeping-dog,2.682023
2,A15312,3653.884565,2.0,5,3.208202,Sleeping-dog,3.208202
3,A16605,3713.211107,2.0,6,0.900000,Early-bird,1.000000
4,B10634,3391.074215,2.0,4,2.453656,Sleeping-dog,2.453656
...,...,...,...,...,...,...,...
145,Z13253,3678.800000,2.0,5,2.463670,Big-Screen-lover,2.463670
146,Z13534,3662.437527,3.0,6,0.900000,Early-bird,1.000000
147,Z16428,3516.500000,2.0,5,2.371301,Big-Screen-lover,2.371301
148,Z16735,3300.100000,2.0,5,1.704942,Big-Screen-lover,1.704942
149,Z19835,3326.526183,2.0,6,1.200000,Early-bird,1.200000

In [16]:
customerData["PRODUCTAGE_NEW"] = \
    np.where( customerData.PRODUCTAGE < 1, 1, customerData.PRODUCTAGE)

In [17]:
# 다중 조건 활용 np.where 적용 문법
customerData["PRODUCTAGE_NEW"] = \
    np.where( customerData.PRODUCTAGE < 1, 1, 
             np.where( customerData.PRODUCTAGE < 2, 2,
                      np.where( customerData.PRODUCTAGE < 3, 3, customerData.PRODUCTAGE)))

In [18]:
### 데이터 조작 pandas
### 사용하는 방법이 람다~
### 1. np.where: 간단한 데이터 처리 시
### 2. loc: 딱 수정포인트만 조건으로 검색해서 수정하고 빠지기
### 3. function: 복잡한 로직인 경우 함수를 정의해서 처리
### 4. dictionary 활용: 딕셔너리 정의 후 매핑: 문자 -> 숫자로 변환
### 5. labelEncoder 활용: 카테고리 데이터를 숫자로 매핑 (근데 카테고리가 많은 경우)
### 6. onehotEncoder 활용: 인공지능에서 이미지 학습   1 -> 00001, 2-> 00010, 3 -> 00100

In [19]:
avgPriceMean = customerData.AVGPRICE.mean()
avgPriceMean

np.float64(3432.7411077064326)

In [20]:
%%timeit
### np.where 활용방법: 데이터프레임명["컬럼명"] = np.where( 조건식, True, False)
customerData["NEW_CAT"] = np.where(customerData.AVGPRICE < avgPriceMean, 0, 1 )
# customerData.loc[ (customerData.NEW_CAT < 1) & (customerData.AVGPRICE >= avgPriceMean) ]

110 μs ± 10.9 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [21]:
%%timeit
### loc 기능 (평균가격보다 작게 구매금액이 형성되어 있으면 -> 0 )
### loc 속도가 좀 np.where보다 떨어진다
customerData.loc[ customerData.AVGPRICE < avgPriceMean, "NEW_CAT2" ] = 0
customerData.loc[ customerData.AVGPRICE >= avgPriceMean, "NEW_CAT2" ] = 1

412 μs ± 27.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [22]:
# customerData.loc[ customerData.NEW_CAT != customerData.NEW_CAT2 ]

In [23]:
def custCategory(inValue):
    ### avgPriceMean : 고객들의 평균 구매가격
    # 각 고객들의 AVGPRICE 값
    # inValue = 2000
    # 리턴 Value
    outValue = 0
    # 각 고객들의 AVGPRICE 가 전체 고객의 평균 AVGPRICE 보다 작으면 0 아니면 1 
    if inValue < avgPriceMean:
        outValue = 0
    else:
        outValue = 1
    return outValue

In [24]:
customerData["NEW_CAT3"] = customerData.AVGPRICE.apply(custCategory)

In [25]:
customerData.loc[ customerData.NEW_CAT != customerData.NEW_CAT3 ]

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE, PRODUCTAGE_NEW, NEW_CAT, NEW_CAT2, NEW_CAT3]
Index: []

### 컬럼간 데이터 연산하기

In [26]:
customerData["EMI_DEVCOUNT"] = customerData.EMI * customerData.DEVICECOUNT
# customerData.CUSTID[0] + "_" + customerData.AVGPRICE
customerData.CUSTID.str[0] + "_" + customerData.AVGPRICE.astype(str)
customerData.CUSTID.str[1:].astype(int) + customerData.AVGPRICE
customerData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW,NEW_CAT,NEW_CAT2,NEW_CAT3,EMI_DEVCOUNT
0,A13566,4273.900000,3.0,6,1.679181,Big-Screen-lover,2.000000,1,1.0,1,18.0
1,A14219,3642.441950,2.0,4,2.682023,Sleeping-dog,3.000000,1,1.0,1,8.0
2,A15312,3653.884565,2.0,5,3.208202,Sleeping-dog,3.208202,1,1.0,1,10.0
3,A16605,3713.211107,2.0,6,0.900000,Early-bird,1.000000,1,1.0,1,12.0
4,B10634,3391.074215,2.0,4,2.453656,Sleeping-dog,3.000000,0,0.0,0,8.0
...,...,...,...,...,...,...,...,...,...,...,...
145,Z13253,3678.800000,2.0,5,2.463670,Big-Screen-lover,3.000000,1,1.0,1,10.0
146,Z13534,3662.437527,3.0,6,0.900000,Early-bird,1.000000,1,1.0,1,18.0
147,Z16428,3516.500000,2.0,5,2.371301,Big-Screen-lover,3.000000,1,1.0,1,10.0
148,Z16735,3300.100000,2.0,5,1.704942,Big-Screen-lover,2.000000,0,0.0,0,10.0
149,Z19835,3326.526183,2.0,6,1.200000,Early-bird,2.000000,0,0.0,0,12.0

### 4. 정렬하기

In [27]:
# 정렬하기
sortKey = ["EMI","AVGPRICE"]
sortedData = customerData.sort_values( by = sortKey, ascending= [True, False] )
sortedData = sortedData.reset_index(drop=True)
sortedData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW,NEW_CAT,NEW_CAT2,NEW_CAT3,EMI_DEVCOUNT
0,K10712,3419.462596,1.0,4,2.825790,Sleeping-dog,3.0,0,0.0,0,4.0
1,O13037,3398.216334,1.0,4,2.994395,Sleeping-dog,3.0,0,0.0,0,4.0
2,I14835,3374.091339,1.0,4,2.749678,Sleeping-dog,3.0,0,0.0,0,4.0
3,M16452,3353.537290,1.0,4,1.940357,Sleeping-dog,2.0,0,0.0,0,4.0
4,C18622,3246.000000,1.0,5,1.891624,Big-Screen-lover,2.0,0,0.0,0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
145,F17131,3179.708359,3.0,6,1.100000,Early-bird,2.0,0,0.0,0,18.0
146,J16445,3041.848186,3.0,6,0.800000,Early-bird,1.0,0,0.0,0,18.0
147,I12899,3018.895637,3.0,6,0.900000,Early-bird,1.0,0,0.0,0,18.0
148,X13390,2947.543982,3.0,6,1.100000,Early-bird,2.0,0,0.0,0,18.0
149,J15083,2811.265932,3.0,6,0.900000,Early-bird,1.0,0,0.0,0,18.0

### 5. 그룹바이

In [28]:
# 고객타입별로 PRODUCTAGE의 평균을 찍어보고 싶다
groupKey = ["CUSTTYPE"]
customerData.groupby(by=groupKey)["PRODUCTAGE"].agg(["mean","max","min","std","sum","count"]).reset_index()

           CUSTTYPE      mean       max       min       std         sum  count
0  Big-Screen-lover  2.193531  3.367229  1.498896  0.445798  109.676567     50
1        Early-bird  0.946000  1.300000  0.800000  0.105386   47.300000     50
2      Sleeping-dog  2.658271  3.483573  1.865857  0.415534  132.913529     50

### 6. 이동평균

In [32]:
kopoData = pd.read_csv("../dataset/kopo_product_volume.csv")

In [ ]:
# ST0001 데이터만 선택
targetProduct = "ST0001"
st0001Data = kopoData.loc[ kopoData.PRODUCTGROUP == targetProduct]
# 데이터를 정렬한다 (기본키): null 가질수 없고 데이터에서 중복을 허락하지 않는 컬럼
# 기본키: REGIONID, PRODUCTGROUP, YEARWEEK
# 파밀리데이터 기본키 (데이터베이스를 SQL)

    REGIONID PRODUCTGROUP  YEARWEEK  VOLUME
0        A01       ST0001    201415  810144
2        A01       ST0001    201418  671464
4        A01       ST0001    201413  470040
6        A01       ST0001    201411  524787
8        A01       ST0001    201416  764927
..       ...          ...       ...     ...
255      A01       ST0001    201609  635412
256      A01       ST0001    201616  658270
259      A01       ST0001    201614  739977
261      A01       ST0001    201641  746061
263      A01       ST0001    201420  645626

[133 rows x 4 columns]

In [59]:
### 중복을 허락하지 않는거는 REGIONID, PRODUCTGROUP, YEARWEEK는 중복이
groupKey = ["REGIONID","PRODUCTGROUP","YEARWEEK"]
testData = st0001Data.groupby(by=groupKey)["VOLUME"].agg(["count"]).reset_index()

testData = testData.rename(columns = {"count":"CNT"})
testData.loc[ testData.CNT != 1 ]
# 삼성SDS 후임.. 1년도.. 단한개의 코드도... 운영계에다 이관을 해본적이 없다!!

Empty DataFrame
Columns: [REGIONID, PRODUCTGROUP, YEARWEEK, CNT]
Index: []

In [ ]:
sortKey = ["REGIONID","PRODUCTGROUP","YEARWEEK"]
### 이동평균 13구간 (왜: 분기별 평균판매량을 13*4 = 52 )
sortedData = st0001Data.sort_values( by = sortKey ).reset_index(drop=True)
sortedData["MA13"] = \
        sortedData.VOLUME.rolling(window=13, center=True, min_periods=1).mean()
# 이동표준편차 5 구간 (최근 한달 기준 + - 변화데이터셋 구축한거다)
sortedData["STD5"] = \
        sortedData.VOLUME.rolling(window=5, center=True, min_periods=1).std()
# 상한선, 하한선 설정
sortedData["UPPER_BAND"] = sortedData.MA13 + sortedData.STD5
sortedData["LOWER_BAND"] = sortedData.MA13 - sortedData.STD5
# 정제된 판매량값
sortedData["REFINED_VOLUME"] = \
np.where(sortedData.MA13 > sortedData.UPPER_BAND, sortedData.UPPER_BAND,
         np.where(sortedData.MA13 < sortedData.LOWER_BAND, sortedData.LOWER_BAND,sortedData.VOLUME ))
sortedData["MA5"] = sortedData.REFINED_VOLUME.rolling(window=5, center=True, min_periods=1).mean()
## 정제된판매량 / 이동평균선 5구간 (한달간의 평균 대비)
sortedData["SEASONALITY"] = np.where( sortedData["MA5"] == 0 , 1, sortedData.REFINED_VOLUME / sortedData.MA5 )
sortedData
### 지역 상품 연주차별 계절성 지수 산출하기 
sortedData["YEAR"] = sortedData.YEARWEEK.astype(str).str[:4]
sortedData["WEEK"] = sortedData.YEARWEEK.astype(str).str[4:]
### 최종 그룹바이
groupKey = ["REGIONID","PRODUCTGROUP","WEEK"]
seasonResult = sortedData.groupby(by=groupKey)["SEASONALITY"].agg(["mean"]).reset_index()
seasonResult = seasonResult.rename(columns = {"mean":"SEASON_MEAN"})
seasonResult

   REGIONID PRODUCTGROUP WEEK  SEASON_MEAN
0       A01       ST0001   01     0.924172
1       A01       ST0001   02     0.909825
2       A01       ST0001   03     0.900726
3       A01       ST0001   04     0.946500
4       A01       ST0001   05     0.949494
5       A01       ST0001   06     1.112679
6       A01       ST0001   07     1.096718
7       A01       ST0001   08     0.936732
8       A01       ST0001   09     0.923232
9       A01       ST0001   10     1.108986
10      A01       ST0001   11     1.053500
11      A01       ST0001   12     0.954487
12      A01       ST0001   13     0.935482
13      A01       ST0001   14     0.810449
14      A01       ST0001   15     1.160789
15      A01       ST0001   16     1.070977
16      A01       ST0001   17     0.977972
17      A01       ST0001   18     0.990233
18      A01       ST0001   19     1.014410
19      A01       ST0001   20     0.986137
20      A01       ST0001   21     0.979310
21      A01       ST0001   22     1.015971
22      A01       ST0001   23     0.999971
23      A01       ST0001   24     0.973914
24      A01       ST0001   25     1.018613
25      A01       ST0001   26     1.021670
26      A01       ST0001   27     0.994139
27      A01       ST0001   28     0.966916
28      A01       ST0001   29     0.994182
29      A01       ST0001   30     1.005897
30      A01       ST0001   31     1.019085
31      A01       ST0001   32     0.962894
32      A01       ST0001   33     0.916172
33      A01       ST0001   34     1.095081
34      A01       ST0001   35     1.067553
35      A01       ST0001   36     1.055582
36      A01       ST0001   37     0.967410
37      A01       ST0001   38     0.984729
38      A01       ST0001   39     0.958441
39      A01       ST0001   40     0.998460
40      A01       ST0001   41     0.966267
41      A01       ST0001   42     1.010692
42      A01       ST0001   43     1.000952
43      A01       ST0001   44     0.986981
44      A01       ST0001   45     0.971404
45      A01       ST0001   46     0.877431
46      A01       ST0001   47     0.877012
47      A01       ST0001   48     1.373231
48      A01       ST0001   49     0.985898
49      A01       ST0001   50     0.791885
50      A01       ST0001   51     0.979647
51      A01       ST0001   52     1.441855
52      A01       ST0001   53     0.970576

In [134]:
sortKey = ["REGIONID","PRODUCTGROUP","YEARWEEK"]
sortData = st0001Data.sort_values(by=sortKey).reset_index(drop=True)
sortData["MA5"] = sortData.VOLUME.rolling(window=3, center=True, min_periods=1).mean()
sortData.loc[ 0:1,["VOLUME"]].mean()
sortData
# 475924.500000

    REGIONID PRODUCTGROUP  YEARWEEK  VOLUME            MA5
0        A01       ST0001    201401  513598  475924.500000
1        A01       ST0001    201402  438251  457379.666667
2        A01       ST0001    201403  420290  438990.666667
3        A01       ST0001    201404  458431  453700.666667
4        A01       ST0001    201405  482381  503741.333333
..       ...          ...       ...     ...            ...
128      A01       ST0001    201623  768124  786236.000000
129      A01       ST0001    201624  772706  775682.666667
130      A01       ST0001    201625  786218  810057.000000
131      A01       ST0001    201626  871247  801175.333333
132      A01       ST0001    201641  746061  808654.000000

[133 rows x 5 columns]

### 7. 데이터 조인

In [142]:
joinMaster = pd.read_csv("../dataset/join_region_master.csv", encoding="ms949")
joinSellout = pd.read_csv("../dataset/join_kopo_product_volume.csv")

In [163]:
# STEP1: 샘플 데이터 생성하기
extraValue = ["A05","ST0005",202520,6000]
# STEP2: 샘플데이터를 데이터프레임 형태로 변환하기
extraData = pd.DataFrame( [ extraValue ] )
extraData.columns = joinSellout.columns
extraData
# STEP3: 기존 joinSellout 데이터와 병합하기 (UNION)
# pd.concat( [  데이터프레임#1, 데이터프레임#2  ])
baseDataUnion = pd.concat( [ joinSellout, extraData ] , axis=0   )
baseDataUnion = baseDataUnion.reset_index(drop=True)
baseDataUnion

  REGIONID PRODUCT  YEARWEEK   QTY
0      A01  ST0001    201901  3000
1      A01  ST0001    201902  3500
2      A02  ST0002    201901  4000
3      A02  ST0003    201902  7000
4      A05  ST0005    202520  6000

In [173]:
### 데이터 조인
joinKey = ["REGIONID"]
### 데이터 조인 (inner, left, right, outer (full_outer) )
joinData = pd.merge( left= baseDataUnion, right = joinMaster, on=joinKey, how="outer")

### 영상_포트폴리오
## 기술적인 트리
## 이동평균 데이터프레임명[타겟컬럼].rolling(window=구간, center=T/F, min_periods=1 )
## UNION = pd.concat( [데이터프레임#1, 데이터프레임#2], axis=0 )
## JOIN = pd.merge(left, right, on, how)

In [193]:
baseDataUnion = baseDataUnion.rename(columns={"REGIONID":"AP2ID"})

In [224]:
## 기존 베이스데이터에 새로 생성한 RATIO 데이터프레임 조인하기
baseDf = pd.merge(  left=baseDataUnion, 
         right=joinMaster, 
         left_on=["AP2ID"], 
         right_on= ["REGIONID"], 
         how="left")
# 컬럼 별로 값이 있을때 데이터프레임 생성하는 방법
targetProduct = ["ST0001", "ST0005"]
targetRatio = [0.5, 0.3]
productCol = pd.DataFrame( targetProduct )
ratioCol = pd.DataFrame(targetRatio)
mergedDf = pd.concat( [productCol,ratioCol ], axis=1)
mergedDf.columns = ["AP2ID","RATIO"]
mergedDf

# 행별로 값이 있을때 데이터프레임 생성하는 방법
row1Data = ["ST0001", 0.5]
row2Data = ["ST0002", 0.3]
mergedDf = pd.DataFrame( [row1Data, row2Data], columns = mergedDf.columns )

In [232]:
pd.merge( left = baseDf, 
         right= mergedDf, 
         left_on=["PRODUCT"],
         right_on=["AP2ID"], 
         how="left")

  AP2ID_x PRODUCT  YEARWEEK   QTY REGIONID REGIONNAME AP2ID_y  RATIO
0     A01  ST0001    201901  3000      A01         한국  ST0001    0.5
1     A01  ST0001    201902  3500      A01         한국  ST0001    0.5
2     A02  ST0002    201901  4000      A02         미국  ST0002    0.3
3     A02  ST0003    201902  7000      A02         미국     NaN    NaN
4     A05  ST0005    202520  6000      NaN        NaN     NaN    NaN

In [189]:
baseDataUnion

  REGIONID PRODUCT  YEARWEEK   QTY
0      A01  ST0001    201901  3000
1      A01  ST0001    201902  3500
2      A02  ST0002    201901  4000
3      A02  ST0003    201902  7000
4      A05  ST0005    202520  6000

In [185]:
joinMaster

  REGIONID REGIONNAME
0      A01         한국
1      A02         미국
2      A03        프랑스
3      A04         독일